
const qualifications = [
  "8th Pass",
  "10th Pass",
  "12th Science",
  "12th Commerce",
  "12th Arts",
  "Diploma - Engineering",
  "Diploma - Non-Engineering",
  "Graduation - Science",
  "Graduation - Commerce",
  "Graduation - Arts",
  "Graduation - Professional (CA, CS, Law)",
  "Post Graduation - Science",
  "Post Graduation - Commerce",
  "Post Graduation - Arts",
  "PhD",
  "International High School Diploma",
  "Online Certifications (AI/ML/Data Science)",
  "Professional Certifications (AWS, PMP, Google, Microsoft)",
];

const exams = {
  govt: [
    "UPSC Civil Services",
    "SSC CGL",
    "IBPS Bank PO",
    "Railway Recruitment Board",
    "State PSC Exams",
    "Defence Services (NDA/CDS/SSB)",
    "PSU Exams (ONGC, NTPC, IOCL, SAIL)",
    "LIC AAO",
    "SSC JE",
  ],
  private: [
    "CAT (MBA entrance)",
    "GRE/GMAT",
    "IELTS/TOEFL",
    "Google Career Certificates",
    "Coursera Specializations",
    "AWS Certification",
    "PMP Certification",
    "Digital Marketing Certification",
  ],
};

const careerGoals = [
  "Software Developer",
  "Data Scientist",
  "Civil Services (IAS/IPS)",
  "Bank PO",
  "Entrepreneur",
  "Teacher/Professor",
  "Researcher",
  "Artist",
  "Sports Professional",
  "Machine Learning Engineer",
  "Product Manager",
  "Digital Marketer",
  "Blockchain Developer",
  "Cybersecurity Specialist",
  "Content Creator/YouTuber",
  "Financial Analyst",
];

const careerPaths = {
  "8th Pass": ["Basic vocational courses", "Apprenticeships", "Skill development programs"],
  "10th Pass": ["ITI courses", "Diploma courses", "Start vocational training", "Apprenticeship"],
  "12th Science": ["Engineering", "Medical", "Pure Science degrees", "Data Science courses"],
  "12th Commerce": ["B.Com", "Chartered Accountancy", "Banking exams preparation"],
  "12th Arts": ["BA", "Civil Services preparation", "Journalism"],
  "Diploma - Engineering": ["Lateral entry to Engineering degree", "Technical jobs"],
  "Diploma - Non-Engineering": ["Job in relevant field", "Professional certificates"],
  "Graduation - Science": ["M.Sc", "Research", "Software Developer", "Data Scientist"],
  "Graduation - Commerce": ["MBA", "Bank PO", "Accounting jobs", "Financial Analyst"],
  "Graduation - Arts": ["MA", "Civil Services", "Teaching", "Content Creation"],
  "Graduation - Professional (CA, CS, Law)": ["Professional practice", "Corporate jobs", "Consulting"],
  "Post Graduation - Science": ["PhD", "Research", "Higher teaching", "Corporate R&D"],
  "Post Graduation - Commerce": ["Higher studies", "Financial services", "Consulting"],
  "Post Graduation - Arts": ["PhD", "Research", "Teaching", "Policy making"],
  "PhD": ["Research", "University professor", "Consulting"],
  "International High School Diploma": ["Apply to International Universities", "Online Courses", "Internships Abroad"],
  "Online Certifications (AI/ML/Data Science)": ["Build Portfolio", "Freelance Projects", "Apply for Tech Jobs"],
  "Professional Certifications (AWS, PMP, Google, Microsoft)": ["Specialize career", "Consulting", "Corporate roles"],
};

const goalPaths = {
  "Software Developer": [
    "Complete B.Tech or relevant degree",
    "Learn programming languages",
    "Internships",
    "Apply to IT companies",
  ],
  "Data Scientist": [
    "Learn statistics and programming",
    "Take AI/ML courses",
    "Work on projects",
    "Apply for data science roles",
  ],
  "Civil Services (IAS/IPS)": [
    "Graduate in any stream",
    "Start UPSC preparation",
    "Appear for exams",
    "Join services",
  ],
  "Bank PO": ["Graduate", "Prepare for banking exams", "Clear exams", "Join banks"],
  "Entrepreneur": ["Identify business idea", "Create business plan", "Raise funds", "Launch startup"],
  "Teacher/Professor": [
    "Complete relevant degree",
    "Clear teaching eligibility tests",
    "Apply for teaching jobs",
  ],
  "Researcher": ["Post graduation", "Join research institutes", "Publish papers"],
  "Artist": ["Develop portfolio", "Take art courses", "Participate in exhibitions"],
  "Sports Professional": ["Train rigorously", "Participate in tournaments", "Join professional clubs"],
  "Machine Learning Engineer": [
    "Complete degree in CS/Math",
    "Specialize in ML/AI courses",
    "Build projects",
    "Apply for ML engineer roles",
  ],
  "Product Manager": [
    "Gain experience in tech or business",
    "Learn product management",
    "Work on projects",
    "Apply to PM roles",
  ],
  "Digital Marketer": [
    "Learn digital marketing skills",
    "Gain certifications",
    "Work on campaigns",
    "Apply to marketing roles",
  ],
  "Blockchain Developer": [
    "Learn blockchain basics",
    "Build decentralized apps",
    "Contribute to open source",
    "Apply to blockchain firms",
  ],
  "Cybersecurity Specialist": [
    "Study cybersecurity concepts",
    "Get certifications (CEH, CISSP)",
    "Work on security projects",
    "Join cybersecurity companies",
  ],
  "Content Creator/YouTuber": [
    "Identify niche",
    "Create content regularly",
    "Grow audience",
    "Monetize platform",
  ],
  "Financial Analyst": [
    "Learn finance and analytics",
    "Gain certifications (CFA)",
    "Work on financial models",
    "Join finance companies",
  ],
};

const backupPlans = {
  "Failed Govt Exams": [
    "Try alternate government exams",
    "Pursue higher education",
    "Explore private sector jobs",
    "Take online skill courses",
  ],
  "Tech Career Roadblocks": [
    "Switch to related fields like testing or support",
    "Take up freelancing",
    "Learn new skills",
    "Consider entrepreneurship",
  ],
  "Entrepreneurship Risks": [
    "Have a fallback job plan",
    "Keep learning business skills",
    "Network extensively",
    "Seek mentorship",
  ],
};
